# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb2fdbc8e936e1934cab626d27bf4b8922b0ab157e78517b9216c865265dd76d895b7f123225f71e44b45dd60e093818c989c10fee408020a6526435792f950

test:
  secret_key_base: 5067fd504d261ff55316f5955f3768bc3f73930b4de4fddc61b0d6e425661ccb4858f6d82dec9380b9ae006472319ee5cd1dc5a3f9223497b424c28c102f3f8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
